---
- name: Install Laravel installer
  become: false
  command: composer global require laravel/installer
  args:
    creates: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/laravel"

- name: Add Composer global bin to PATH in shell configs
  become: false
  lineinfile:
    path: "{{ item }}"
    regexp: '^export PATH=.*\.config/composer/vendor/bin'
    line: 'export PATH="$HOME/.config/composer/vendor/bin:$PATH"'
    create: yes
  loop:
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.zshrc"
