---
- name: Add NodeSource GPG key
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
  args:
    creates: /usr/share/keyrings/nodesource.gpg

- name: Add NodeSource repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    state: present
    filename: nodesource

- name: Update apt cache after adding NodeSource repo
  apt:
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present
