---
- name: Create MariaDB/MySQL databases
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ databases }}"
  when: "db_type in ['mariadb', 'mysql']"
  ignore_errors: yes

- name: Create PostgreSQL databases
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    state: present
  loop: "{{ databases }}"
  when: "db_type == 'postgresql'"
  ignore_errors: yes
